FROM python:3.8

RUN pip install --upgrade pip
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

COPY . /app

ENV PYTHONUNBUFFERED=1

CMD python manage.py makemigrations
CMD python manage.py runserver 0.0.0.0:8000
